[package]
name = "relmetric"
version = "0.1.0"
edition = "2021"
authors = ["Ken Ewing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
